{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_github","uid":"7c4a9481a648b78f","parentUid":"ddf09d51cb39ced0e25ca425ac775194","status":"broken","time":{"start":1688896064169,"stop":1688896064169,"duration":0},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ddf09d51cb39ced0e25ca425ac775194"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a1147010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_dynamic_steps","uid":"2d53d70dc984c809","parentUid":"dc8d14778c6ebbfa51434809fe100fb9","status":"broken","time":{"start":1688896064359,"stop":1688896064359,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"dc8d14778c6ebbfa51434809fe100fb9"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}