{"uid":"7c4a9481a648b78f","name":"test_github","fullName":"tests.test_selene#test_github","historyId":"5167f7c71535600a353c42dca9c39857","time":{"start":1688896064169,"stop":1688896064169,"duration":0},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"self = <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>\n\n    def _new_conn(self) -> socket.socket:\n        \"\"\"Establish a socket connection and set nodelay settings on it.\n    \n        :return: New socket connection.\n        \"\"\"\n        try:\n>           sock = connection.create_connection(\n                (self._dns_host, self.port),\n                self.timeout,\n                source_address=self.source_address,\n                socket_options=self.socket_options,\n            )\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/connection.py:85: in create_connection\n    raise err\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\naddress = ('localhost', 56557), timeout = None, source_address = None\nsocket_options = [(6, 1, 1)]\n\n    def create_connection(\n        address: tuple[str, int],\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        source_address: tuple[str, int] | None = None,\n        socket_options: _TYPE_SOCKET_OPTIONS | None = None,\n    ) -> socket.socket:\n        \"\"\"Connect to *address* and return the socket object.\n    \n        Convenience function.  Connect to *address* (a 2-tuple ``(host,\n        port)``) and return the socket object.  Passing the optional\n        *timeout* parameter will set the timeout on the socket instance\n        before attempting to connect.  If no *timeout* is supplied, the\n        global default timeout setting returned by :func:`socket.getdefaulttimeout`\n        is used.  If *source_address* is set it must be a tuple of (host, port)\n        for the socket to bind as a source address before making the connection.\n        An host of '' or port 0 tells the OS to use the default.\n        \"\"\"\n    \n        host, port = address\n        if host.startswith(\"[\"):\n            host = host.strip(\"[]\")\n        err = None\n    \n        # Using the value from allowed_gai_family() in the context of getaddrinfo lets\n        # us select whether to work with IPv4 DNS records, IPv6 records, or both.\n        # The original create_connection function always returns all records.\n        family = allowed_gai_family()\n    \n        try:\n            host.encode(\"idna\")\n        except UnicodeError:\n            raise LocationParseError(f\"'{host}', label empty or too long\") from None\n    \n        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n            af, socktype, proto, canonname, sa = res\n            sock = None\n            try:\n                sock = socket.socket(af, socktype, proto)\n    \n                # If provided, set socket level options before connecting.\n                _set_socket_options(sock, socket_options)\n    \n                if timeout is not _DEFAULT_TIMEOUT:\n                    sock.settimeout(timeout)\n                if source_address:\n                    sock.bind(source_address)\n>               sock.connect(sa)\nE               ConnectionRefusedError: [Errno 111] Connection refused\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/connection.py:73: ConnectionRefusedError\n\nThe above exception was the direct cause of the following exception:\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x7f63a2713b10>\nmethod = 'POST'\nurl = '/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize', body = '{}'\nheaders = HTTPHeaderDict({'Accept': 'application/json', 'Content-Type': 'application/json;charset=UTF-8', 'User-Agent': 'selenium/4.10.0 (python linux)', 'Connection': 'keep-alive'})\nretries = Retry(total=0, connect=None, read=None, redirect=None, status=None)\nredirect = False, assert_same_host = False, timeout = <_TYPE_DEFAULT.token: -1>\npool_timeout = None, release_conn = True, chunked = False, body_pos = None\npreload_content = True, decode_content = True, response_kw = {}\nparsed_url = Url(scheme=None, auth=None, host=None, port=None, path='/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize', query=None, fragment=None)\ndestination_scheme = None, conn = None, release_this_conn = True\nhttp_tunnel_required = False, err = None, clean_exit = False\n\n    def urlopen(  # type: ignore[override]\n        self,\n        method: str,\n        url: str,\n        body: _TYPE_BODY | None = None,\n        headers: typing.Mapping[str, str] | None = None,\n        retries: Retry | bool | int | None = None,\n        redirect: bool = True,\n        assert_same_host: bool = True,\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        pool_timeout: int | None = None,\n        release_conn: bool | None = None,\n        chunked: bool = False,\n        body_pos: _TYPE_BODY_POSITION | None = None,\n        preload_content: bool = True,\n        decode_content: bool = True,\n        **response_kw: typing.Any,\n    ) -> BaseHTTPResponse:\n        \"\"\"\n        Get a connection from the pool and perform an HTTP request. This is the\n        lowest level call for making a request, so you'll need to specify all\n        the raw details.\n    \n        .. note::\n    \n           More commonly, it's appropriate to use a convenience method\n           such as :meth:`request`.\n    \n        .. note::\n    \n           `release_conn` will only behave as expected if\n           `preload_content=False` because we want to make\n           `preload_content=False` the default behaviour someday soon without\n           breaking backwards compatibility.\n    \n        :param method:\n            HTTP request method (such as GET, POST, PUT, etc.)\n    \n        :param url:\n            The URL to perform the request on.\n    \n        :param body:\n            Data to send in the request body, either :class:`str`, :class:`bytes`,\n            an iterable of :class:`str`/:class:`bytes`, or a file-like object.\n    \n        :param headers:\n            Dictionary of custom headers to send, such as User-Agent,\n            If-None-Match, etc. If None, pool headers are used. If provided,\n            these headers completely replace any pool-specific headers.\n    \n        :param retries:\n            Configure the number of retries to allow before raising a\n            :class:`~urllib3.exceptions.MaxRetryError` exception.\n    \n            Pass ``None`` to retry until you receive a response. Pass a\n            :class:`~urllib3.util.retry.Retry` object for fine-grained control\n            over different types of retries.\n            Pass an integer number to retry connection errors that many times,\n            but no other types of errors. Pass zero to never retry.\n    \n            If ``False``, then retries are disabled and any exception is raised\n            immediately. Also, instead of raising a MaxRetryError on redirects,\n            the redirect response will be returned.\n    \n        :type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.\n    \n        :param redirect:\n            If True, automatically handle redirects (status codes 301, 302,\n            303, 307, 308). Each redirect counts as a retry. Disabling retries\n            will disable redirect, too.\n    \n        :param assert_same_host:\n            If ``True``, will make sure that the host of the pool requests is\n            consistent else will raise HostChangedError. When ``False``, you can\n            use the pool on an HTTP proxy and request foreign hosts.\n    \n        :param timeout:\n            If specified, overrides the default timeout for this one\n            request. It may be a float (in seconds) or an instance of\n            :class:`urllib3.util.Timeout`.\n    \n        :param pool_timeout:\n            If set and the pool is set to block=True, then this method will\n            block for ``pool_timeout`` seconds and raise EmptyPoolError if no\n            connection is available within the time period.\n    \n        :param bool preload_content:\n            If True, the response's body will be preloaded into memory.\n    \n        :param bool decode_content:\n            If True, will attempt to decode the body based on the\n            'content-encoding' header.\n    \n        :param release_conn:\n            If False, then the urlopen call will not release the connection\n            back into the pool once a response is received (but will release if\n            you read the entire contents of the response such as when\n            `preload_content=True`). This is useful if you're not preloading\n            the response's content immediately. You will need to call\n            ``r.release_conn()`` on the response ``r`` to return the connection\n            back into the pool. If None, it takes the value of ``preload_content``\n            which defaults to ``True``.\n    \n        :param bool chunked:\n            If True, urllib3 will send the body using chunked transfer\n            encoding. Otherwise, urllib3 will send the body using the standard\n            content-length form. Defaults to False.\n    \n        :param int body_pos:\n            Position to seek to in file-like body in the event of a retry or\n            redirect. Typically this won't need to be set because urllib3 will\n            auto-populate the value when needed.\n        \"\"\"\n        parsed_url = parse_url(url)\n        destination_scheme = parsed_url.scheme\n    \n        if headers is None:\n            headers = self.headers\n    \n        if not isinstance(retries, Retry):\n            retries = Retry.from_int(retries, redirect=redirect, default=self.retries)\n    \n        if release_conn is None:\n            release_conn = preload_content\n    \n        # Check host\n        if assert_same_host and not self.is_same_host(url):\n            raise HostChangedError(self, url, retries)\n    \n        # Ensure that the URL we're connecting to is properly encoded\n        if url.startswith(\"/\"):\n            url = to_str(_encode_target(url))\n        else:\n            url = to_str(parsed_url.url)\n    \n        conn = None\n    \n        # Track whether `conn` needs to be released before\n        # returning/raising/recursing. Update this variable if necessary, and\n        # leave `release_conn` constant throughout the function. That way, if\n        # the function recurses, the original value of `release_conn` will be\n        # passed down into the recursive call, and its value will be respected.\n        #\n        # See issue #651 [1] for details.\n        #\n        # [1] <https://github.com/urllib3/urllib3/issues/651>\n        release_this_conn = release_conn\n    \n        http_tunnel_required = connection_requires_http_tunnel(\n            self.proxy, self.proxy_config, destination_scheme\n        )\n    \n        # Merge the proxy headers. Only done when not using HTTP CONNECT. We\n        # have to copy the headers dict so we can safely change it without those\n        # changes being reflected in anyone else's copy.\n        if not http_tunnel_required:\n            headers = headers.copy()  # type: ignore[attr-defined]\n            headers.update(self.proxy_headers)  # type: ignore[union-attr]\n    \n        # Must keep the exception bound to a separate variable or else Python 3\n        # complains about UnboundLocalError.\n        err = None\n    \n        # Keep track of whether we cleanly exited the except block. This\n        # ensures we do proper cleanup in finally.\n        clean_exit = False\n    \n        # Rewind body position, if needed. Record current position\n        # for future rewinds in the event of a redirect/retry.\n        body_pos = set_file_position(body, body_pos)\n    \n        try:\n            # Request a connection from the queue.\n            timeout_obj = self._get_timeout(timeout)\n            conn = self._get_conn(timeout=pool_timeout)\n    \n            conn.timeout = timeout_obj.connect_timeout  # type: ignore[assignment]\n    \n            # Is this a closed/new connection that requires CONNECT tunnelling?\n            if self.proxy is not None and http_tunnel_required and conn.is_closed:\n                try:\n                    self._prepare_proxy(conn)\n                except (BaseSSLError, OSError, SocketTimeout) as e:\n                    self._raise_timeout(\n                        err=e, url=self.proxy.url, timeout_value=conn.timeout\n                    )\n                    raise\n    \n            # If we're going to release the connection in ``finally:``, then\n            # the response doesn't need to know about the connection. Otherwise\n            # it will also try to release it and we'll have a double-release\n            # mess.\n            response_conn = conn if not release_conn else None\n    \n            # Make the request on the HTTPConnection object\n>           response = self._make_request(\n                conn,\n                method,\n                url,\n                timeout=timeout_obj,\n                body=body,\n                headers=headers,\n                chunked=chunked,\n                retries=retries,\n                response_conn=response_conn,\n                preload_content=preload_content,\n                decode_content=decode_content,\n                **response_kw,\n            )\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:790: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:496: in _make_request\n    conn.request(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:388: in request\n    self.endheaders()\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:1281: in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:1041: in _send_output\n    self.send(msg)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:979: in send\n    self.connect()\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:236: in connect\n    self.sock = self._new_conn()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>\n\n    def _new_conn(self) -> socket.socket:\n        \"\"\"Establish a socket connection and set nodelay settings on it.\n    \n        :return: New socket connection.\n        \"\"\"\n        try:\n            sock = connection.create_connection(\n                (self._dns_host, self.port),\n                self.timeout,\n                source_address=self.source_address,\n                socket_options=self.socket_options,\n            )\n        except socket.gaierror as e:\n            raise NameResolutionError(self.host, self, e) from e\n        except SocketTimeout as e:\n            raise ConnectTimeoutError(\n                self,\n                f\"Connection to {self.host} timed out. (connect timeout={self.timeout})\",\n            ) from e\n    \n        except OSError as e:\n>           raise NewConnectionError(\n                self, f\"Failed to establish a new connection: {e}\"\n            ) from e\nE           urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:215: NewConnectionError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture(autouse=True)\n    def driver():\n        options = webdriver.ChromeOptions()\n        options.add_argument(\"--headless\")\n        options.add_argument(\"--disable-gpu\")\n        options.add_argument(\"--window-size=1920,1080\")\n        browser.config.driver_options = options\n>       browser.config.driver.maximize_window()\n\ntests/conftest.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:498: in maximize_window\n    self.execute(command, None)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    response = self.command_executor.execute(driver_command, params)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:290: in execute\n    return self._request(command_info[0], url, body=data)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:311: in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py:118: in request\n    return self.request_encode_body(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py:217: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/poolmanager.py:443: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Retry(total=0, connect=None, read=None, redirect=None, status=None)\nmethod = 'POST'\nurl = '/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize'\nresponse = None\nerror = NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused')\n_pool = <urllib3.connectionpool.HTTPConnectionPool object at 0x7f63a2713b10>\n_stacktrace = <traceback object at 0x7f63a25cd700>\n\n    def increment(\n        self,\n        method: str | None = None,\n        url: str | None = None,\n        response: BaseHTTPResponse | None = None,\n        error: Exception | None = None,\n        _pool: ConnectionPool | None = None,\n        _stacktrace: TracebackType | None = None,\n    ) -> Retry:\n        \"\"\"Return a new Retry object with incremented retry counters.\n    \n        :param response: A response object, or None, if the server did not\n            return a response.\n        :type response: :class:`~urllib3.response.BaseHTTPResponse`\n        :param Exception error: An error encountered during the request, or\n            None if the response was received successfully.\n    \n        :return: A new ``Retry`` object.\n        \"\"\"\n        if self.total is False and error:\n            # Disabled, indicate to re-raise the error.\n            raise reraise(type(error), error, _stacktrace)\n    \n        total = self.total\n        if total is not None:\n            total -= 1\n    \n        connect = self.connect\n        read = self.read\n        redirect = self.redirect\n        status_count = self.status\n        other = self.other\n        cause = \"unknown\"\n        status = None\n        redirect_location = None\n    \n        if error and self._is_connection_error(error):\n            # Connect retry?\n            if connect is False:\n                raise reraise(type(error), error, _stacktrace)\n            elif connect is not None:\n                connect -= 1\n    \n        elif error and self._is_read_error(error):\n            # Read retry?\n            if read is False or method is None or not self._is_method_retryable(method):\n                raise reraise(type(error), error, _stacktrace)\n            elif read is not None:\n                read -= 1\n    \n        elif error:\n            # Other retry?\n            if other is not None:\n                other -= 1\n    \n        elif response and response.get_redirect_location():\n            # Redirect retry?\n            if redirect is not None:\n                redirect -= 1\n            cause = \"too many redirects\"\n            response_redirect_location = response.get_redirect_location()\n            if response_redirect_location:\n                redirect_location = response_redirect_location\n            status = response.status\n    \n        else:\n            # Incrementing because of a server error like a 500 in\n            # status_forcelist and the given method is in the allowed_methods\n            cause = ResponseError.GENERIC_ERROR\n            if response and response.status:\n                if status_count is not None:\n                    status_count -= 1\n                cause = ResponseError.SPECIFIC_ERROR.format(status_code=response.status)\n                status = response.status\n    \n        history = self.history + (\n            RequestHistory(method, url, error, status, redirect_location),\n        )\n    \n        new_retry = self.new(\n            total=total,\n            connect=connect,\n            read=read,\n            redirect=redirect,\n            status=status_count,\n            other=other,\n            history=history,\n        )\n    \n        if new_retry.is_exhausted():\n            reason = error or ResponseError(cause)\n>           raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nE           urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/retry.py:515: MaxRetryError","flaky":true,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1688896064170,"stop":1688896064173,"duration":3},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/qaguru/qaguru/tests/conftest.py\", line 13, in driver\n    browser.config.driver.maximize_window()\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 498, in maximize_window\n    self.execute(command, None)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 118, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 217, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"self = <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>\n\n    def _new_conn(self) -> socket.socket:\n        \"\"\"Establish a socket connection and set nodelay settings on it.\n    \n        :return: New socket connection.\n        \"\"\"\n        try:\n>           sock = connection.create_connection(\n                (self._dns_host, self.port),\n                self.timeout,\n                source_address=self.source_address,\n                socket_options=self.socket_options,\n            )\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/connection.py:85: in create_connection\n    raise err\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\naddress = ('localhost', 56557), timeout = None, source_address = None\nsocket_options = [(6, 1, 1)]\n\n    def create_connection(\n        address: tuple[str, int],\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        source_address: tuple[str, int] | None = None,\n        socket_options: _TYPE_SOCKET_OPTIONS | None = None,\n    ) -> socket.socket:\n        \"\"\"Connect to *address* and return the socket object.\n    \n        Convenience function.  Connect to *address* (a 2-tuple ``(host,\n        port)``) and return the socket object.  Passing the optional\n        *timeout* parameter will set the timeout on the socket instance\n        before attempting to connect.  If no *timeout* is supplied, the\n        global default timeout setting returned by :func:`socket.getdefaulttimeout`\n        is used.  If *source_address* is set it must be a tuple of (host, port)\n        for the socket to bind as a source address before making the connection.\n        An host of '' or port 0 tells the OS to use the default.\n        \"\"\"\n    \n        host, port = address\n        if host.startswith(\"[\"):\n            host = host.strip(\"[]\")\n        err = None\n    \n        # Using the value from allowed_gai_family() in the context of getaddrinfo lets\n        # us select whether to work with IPv4 DNS records, IPv6 records, or both.\n        # The original create_connection function always returns all records.\n        family = allowed_gai_family()\n    \n        try:\n            host.encode(\"idna\")\n        except UnicodeError:\n            raise LocationParseError(f\"'{host}', label empty or too long\") from None\n    \n        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n            af, socktype, proto, canonname, sa = res\n            sock = None\n            try:\n                sock = socket.socket(af, socktype, proto)\n    \n                # If provided, set socket level options before connecting.\n                _set_socket_options(sock, socket_options)\n    \n                if timeout is not _DEFAULT_TIMEOUT:\n                    sock.settimeout(timeout)\n                if source_address:\n                    sock.bind(source_address)\n>               sock.connect(sa)\nE               ConnectionRefusedError: [Errno 111] Connection refused\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/connection.py:73: ConnectionRefusedError\n\nThe above exception was the direct cause of the following exception:\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x7f63a2713b10>\nmethod = 'POST'\nurl = '/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize', body = '{}'\nheaders = HTTPHeaderDict({'Accept': 'application/json', 'Content-Type': 'application/json;charset=UTF-8', 'User-Agent': 'selenium/4.10.0 (python linux)', 'Connection': 'keep-alive'})\nretries = Retry(total=0, connect=None, read=None, redirect=None, status=None)\nredirect = False, assert_same_host = False, timeout = <_TYPE_DEFAULT.token: -1>\npool_timeout = None, release_conn = True, chunked = False, body_pos = None\npreload_content = True, decode_content = True, response_kw = {}\nparsed_url = Url(scheme=None, auth=None, host=None, port=None, path='/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize', query=None, fragment=None)\ndestination_scheme = None, conn = None, release_this_conn = True\nhttp_tunnel_required = False, err = None, clean_exit = False\n\n    def urlopen(  # type: ignore[override]\n        self,\n        method: str,\n        url: str,\n        body: _TYPE_BODY | None = None,\n        headers: typing.Mapping[str, str] | None = None,\n        retries: Retry | bool | int | None = None,\n        redirect: bool = True,\n        assert_same_host: bool = True,\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        pool_timeout: int | None = None,\n        release_conn: bool | None = None,\n        chunked: bool = False,\n        body_pos: _TYPE_BODY_POSITION | None = None,\n        preload_content: bool = True,\n        decode_content: bool = True,\n        **response_kw: typing.Any,\n    ) -> BaseHTTPResponse:\n        \"\"\"\n        Get a connection from the pool and perform an HTTP request. This is the\n        lowest level call for making a request, so you'll need to specify all\n        the raw details.\n    \n        .. note::\n    \n           More commonly, it's appropriate to use a convenience method\n           such as :meth:`request`.\n    \n        .. note::\n    \n           `release_conn` will only behave as expected if\n           `preload_content=False` because we want to make\n           `preload_content=False` the default behaviour someday soon without\n           breaking backwards compatibility.\n    \n        :param method:\n            HTTP request method (such as GET, POST, PUT, etc.)\n    \n        :param url:\n            The URL to perform the request on.\n    \n        :param body:\n            Data to send in the request body, either :class:`str`, :class:`bytes`,\n            an iterable of :class:`str`/:class:`bytes`, or a file-like object.\n    \n        :param headers:\n            Dictionary of custom headers to send, such as User-Agent,\n            If-None-Match, etc. If None, pool headers are used. If provided,\n            these headers completely replace any pool-specific headers.\n    \n        :param retries:\n            Configure the number of retries to allow before raising a\n            :class:`~urllib3.exceptions.MaxRetryError` exception.\n    \n            Pass ``None`` to retry until you receive a response. Pass a\n            :class:`~urllib3.util.retry.Retry` object for fine-grained control\n            over different types of retries.\n            Pass an integer number to retry connection errors that many times,\n            but no other types of errors. Pass zero to never retry.\n    \n            If ``False``, then retries are disabled and any exception is raised\n            immediately. Also, instead of raising a MaxRetryError on redirects,\n            the redirect response will be returned.\n    \n        :type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.\n    \n        :param redirect:\n            If True, automatically handle redirects (status codes 301, 302,\n            303, 307, 308). Each redirect counts as a retry. Disabling retries\n            will disable redirect, too.\n    \n        :param assert_same_host:\n            If ``True``, will make sure that the host of the pool requests is\n            consistent else will raise HostChangedError. When ``False``, you can\n            use the pool on an HTTP proxy and request foreign hosts.\n    \n        :param timeout:\n            If specified, overrides the default timeout for this one\n            request. It may be a float (in seconds) or an instance of\n            :class:`urllib3.util.Timeout`.\n    \n        :param pool_timeout:\n            If set and the pool is set to block=True, then this method will\n            block for ``pool_timeout`` seconds and raise EmptyPoolError if no\n            connection is available within the time period.\n    \n        :param bool preload_content:\n            If True, the response's body will be preloaded into memory.\n    \n        :param bool decode_content:\n            If True, will attempt to decode the body based on the\n            'content-encoding' header.\n    \n        :param release_conn:\n            If False, then the urlopen call will not release the connection\n            back into the pool once a response is received (but will release if\n            you read the entire contents of the response such as when\n            `preload_content=True`). This is useful if you're not preloading\n            the response's content immediately. You will need to call\n            ``r.release_conn()`` on the response ``r`` to return the connection\n            back into the pool. If None, it takes the value of ``preload_content``\n            which defaults to ``True``.\n    \n        :param bool chunked:\n            If True, urllib3 will send the body using chunked transfer\n            encoding. Otherwise, urllib3 will send the body using the standard\n            content-length form. Defaults to False.\n    \n        :param int body_pos:\n            Position to seek to in file-like body in the event of a retry or\n            redirect. Typically this won't need to be set because urllib3 will\n            auto-populate the value when needed.\n        \"\"\"\n        parsed_url = parse_url(url)\n        destination_scheme = parsed_url.scheme\n    \n        if headers is None:\n            headers = self.headers\n    \n        if not isinstance(retries, Retry):\n            retries = Retry.from_int(retries, redirect=redirect, default=self.retries)\n    \n        if release_conn is None:\n            release_conn = preload_content\n    \n        # Check host\n        if assert_same_host and not self.is_same_host(url):\n            raise HostChangedError(self, url, retries)\n    \n        # Ensure that the URL we're connecting to is properly encoded\n        if url.startswith(\"/\"):\n            url = to_str(_encode_target(url))\n        else:\n            url = to_str(parsed_url.url)\n    \n        conn = None\n    \n        # Track whether `conn` needs to be released before\n        # returning/raising/recursing. Update this variable if necessary, and\n        # leave `release_conn` constant throughout the function. That way, if\n        # the function recurses, the original value of `release_conn` will be\n        # passed down into the recursive call, and its value will be respected.\n        #\n        # See issue #651 [1] for details.\n        #\n        # [1] <https://github.com/urllib3/urllib3/issues/651>\n        release_this_conn = release_conn\n    \n        http_tunnel_required = connection_requires_http_tunnel(\n            self.proxy, self.proxy_config, destination_scheme\n        )\n    \n        # Merge the proxy headers. Only done when not using HTTP CONNECT. We\n        # have to copy the headers dict so we can safely change it without those\n        # changes being reflected in anyone else's copy.\n        if not http_tunnel_required:\n            headers = headers.copy()  # type: ignore[attr-defined]\n            headers.update(self.proxy_headers)  # type: ignore[union-attr]\n    \n        # Must keep the exception bound to a separate variable or else Python 3\n        # complains about UnboundLocalError.\n        err = None\n    \n        # Keep track of whether we cleanly exited the except block. This\n        # ensures we do proper cleanup in finally.\n        clean_exit = False\n    \n        # Rewind body position, if needed. Record current position\n        # for future rewinds in the event of a redirect/retry.\n        body_pos = set_file_position(body, body_pos)\n    \n        try:\n            # Request a connection from the queue.\n            timeout_obj = self._get_timeout(timeout)\n            conn = self._get_conn(timeout=pool_timeout)\n    \n            conn.timeout = timeout_obj.connect_timeout  # type: ignore[assignment]\n    \n            # Is this a closed/new connection that requires CONNECT tunnelling?\n            if self.proxy is not None and http_tunnel_required and conn.is_closed:\n                try:\n                    self._prepare_proxy(conn)\n                except (BaseSSLError, OSError, SocketTimeout) as e:\n                    self._raise_timeout(\n                        err=e, url=self.proxy.url, timeout_value=conn.timeout\n                    )\n                    raise\n    \n            # If we're going to release the connection in ``finally:``, then\n            # the response doesn't need to know about the connection. Otherwise\n            # it will also try to release it and we'll have a double-release\n            # mess.\n            response_conn = conn if not release_conn else None\n    \n            # Make the request on the HTTPConnection object\n>           response = self._make_request(\n                conn,\n                method,\n                url,\n                timeout=timeout_obj,\n                body=body,\n                headers=headers,\n                chunked=chunked,\n                retries=retries,\n                response_conn=response_conn,\n                preload_content=preload_content,\n                decode_content=decode_content,\n                **response_kw,\n            )\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:790: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:496: in _make_request\n    conn.request(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:388: in request\n    self.endheaders()\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:1281: in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:1041: in _send_output\n    self.send(msg)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/http/client.py:979: in send\n    self.connect()\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:236: in connect\n    self.sock = self._new_conn()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>\n\n    def _new_conn(self) -> socket.socket:\n        \"\"\"Establish a socket connection and set nodelay settings on it.\n    \n        :return: New socket connection.\n        \"\"\"\n        try:\n            sock = connection.create_connection(\n                (self._dns_host, self.port),\n                self.timeout,\n                source_address=self.source_address,\n                socket_options=self.socket_options,\n            )\n        except socket.gaierror as e:\n            raise NameResolutionError(self.host, self, e) from e\n        except SocketTimeout as e:\n            raise ConnectTimeoutError(\n                self,\n                f\"Connection to {self.host} timed out. (connect timeout={self.timeout})\",\n            ) from e\n    \n        except OSError as e:\n>           raise NewConnectionError(\n                self, f\"Failed to establish a new connection: {e}\"\n            ) from e\nE           urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connection.py:215: NewConnectionError\n\nThe above exception was the direct cause of the following exception:\n\n    @pytest.fixture(autouse=True)\n    def driver():\n        options = webdriver.ChromeOptions()\n        options.add_argument(\"--headless\")\n        options.add_argument(\"--disable-gpu\")\n        options.add_argument(\"--window-size=1920,1080\")\n        browser.config.driver_options = options\n>       browser.config.driver.maximize_window()\n\ntests/conftest.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:498: in maximize_window\n    self.execute(command, None)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    response = self.command_executor.execute(driver_command, params)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:290: in execute\n    return self._request(command_info[0], url, body=data)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py:311: in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py:118: in request\n    return self.request_encode_body(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/_request_methods.py:217: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/poolmanager.py:443: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:874: in urlopen\n    return self.urlopen(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = Retry(total=0, connect=None, read=None, redirect=None, status=None)\nmethod = 'POST'\nurl = '/session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize'\nresponse = None\nerror = NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused')\n_pool = <urllib3.connectionpool.HTTPConnectionPool object at 0x7f63a2713b10>\n_stacktrace = <traceback object at 0x7f63a25cd700>\n\n    def increment(\n        self,\n        method: str | None = None,\n        url: str | None = None,\n        response: BaseHTTPResponse | None = None,\n        error: Exception | None = None,\n        _pool: ConnectionPool | None = None,\n        _stacktrace: TracebackType | None = None,\n    ) -> Retry:\n        \"\"\"Return a new Retry object with incremented retry counters.\n    \n        :param response: A response object, or None, if the server did not\n            return a response.\n        :type response: :class:`~urllib3.response.BaseHTTPResponse`\n        :param Exception error: An error encountered during the request, or\n            None if the response was received successfully.\n    \n        :return: A new ``Retry`` object.\n        \"\"\"\n        if self.total is False and error:\n            # Disabled, indicate to re-raise the error.\n            raise reraise(type(error), error, _stacktrace)\n    \n        total = self.total\n        if total is not None:\n            total -= 1\n    \n        connect = self.connect\n        read = self.read\n        redirect = self.redirect\n        status_count = self.status\n        other = self.other\n        cause = \"unknown\"\n        status = None\n        redirect_location = None\n    \n        if error and self._is_connection_error(error):\n            # Connect retry?\n            if connect is False:\n                raise reraise(type(error), error, _stacktrace)\n            elif connect is not None:\n                connect -= 1\n    \n        elif error and self._is_read_error(error):\n            # Read retry?\n            if read is False or method is None or not self._is_method_retryable(method):\n                raise reraise(type(error), error, _stacktrace)\n            elif read is not None:\n                read -= 1\n    \n        elif error:\n            # Other retry?\n            if other is not None:\n                other -= 1\n    \n        elif response and response.get_redirect_location():\n            # Redirect retry?\n            if redirect is not None:\n                redirect -= 1\n            cause = \"too many redirects\"\n            response_redirect_location = response.get_redirect_location()\n            if response_redirect_location:\n                redirect_location = response_redirect_location\n            status = response.status\n    \n        else:\n            # Incrementing because of a server error like a 500 in\n            # status_forcelist and the given method is in the allowed_methods\n            cause = ResponseError.GENERIC_ERROR\n            if response and response.status:\n                if status_count is not None:\n                    status_count -= 1\n                cause = ResponseError.SPECIFIC_ERROR.format(status_code=response.status)\n                status = response.status\n    \n        history = self.history + (\n            RequestHistory(method, url, error, status, redirect_location),\n        )\n    \n        new_retry = self.new(\n            total=total,\n            connect=connect,\n            read=read,\n            redirect=redirect,\n            status=status_count,\n            other=other,\n            history=history,\n        )\n    \n        if new_retry.is_exhausted():\n            reason = error or ResponseError(cause)\n>           raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\nE           urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56557): Max retries exceeded with url: /session/d5ed28fbe2a1b6e9407e03093e533651/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63a25cd6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/urllib3/util/retry.py:515: MaxRetryError","steps":[],"attachments":[{"uid":"950539251caff1b","name":"log","source":"950539251caff1b.txt","type":"text/plain","size":1121}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"story","value":"Находим в репозитории issue с номером 76"},{"name":"owner","value":"t-rexamarin"},{"name":"tag","value":"web"},{"name":"feature","value":"Задачи в репозитории"},{"name":"severity","value":"normal"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_selene"},{"name":"host","value":"fv-az193-247"},{"name":"thread","value":"2376-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_selene"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","owner":"t-rexamarin","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":3,"broken":16,"skipped":0,"passed":1,"unknown":0,"total":20},"items":[{"uid":"147c37543aec9a4b","reportUrl":"https://t-rexamarin.github.io/qaguru/20//#testresult/147c37543aec9a4b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53727): Max retries exceeded with url: /session/2a5fb67aa6ec8d61141542601b855b41/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feff28be590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1688895705067,"stop":1688895705067,"duration":0}},{"uid":"3b2fdcc37ef37a48","reportUrl":"https://t-rexamarin.github.io/qaguru/20//#testresult/3b2fdcc37ef37a48","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54101): Max retries exceeded with url: /session/ae9518916230a560426e366287142165/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1633d050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1688895570082,"stop":1688895570082,"duration":0}},{"uid":"6e379d5bd7417c34","reportUrl":"https://t-rexamarin.github.io/qaguru/19//#testresult/6e379d5bd7417c34","status":"passed","time":{"start":1688674570093,"stop":1688674572648,"duration":2555}},{"uid":"81ab54998dda316b","reportUrl":"https://t-rexamarin.github.io/qaguru/18//#testresult/81ab54998dda316b","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 10s, while waiting for:\nbrowser.element(('css selector', '.header-search-input')).click\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".header-search-input\"}\n  (Session info: headless chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55fd4a3f44e3 <unknown>\n#1 0x55fd4a123c76 <unknown>\n#2 0x55fd4a15fc96 <unknown>\n#3 0x55fd4a15fdc1 <unknown>\n#4 0x55fd4a1997f4 <unknown>\n#5 0x55fd4a17f03d <unknown>\n#6 0x55fd4a19730e <unknown>\n#7 0x55fd4a17ede3 <unknown>\n#8 0x55fd4a1542dd <unknown>\n#9 0x55fd4a15534e <unknown>\n#10 0x55fd4a3b43e4 <unknown>\n#11 0x55fd4a3b83d7 <unknown>\n#12 0x55fd4a3c2b20 <unknown>\n#13 0x55fd4a3b9023 <unknown>\n#14 0x55fd4a3871aa <unknown>\n#15 0x55fd4a3dd6b8 <unknown>\n#16 0x55fd4a3dd847 <unknown>\n#17 0x55fd4a3ed243 <unknown>\n#18 0x7f4dadd32b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1688674327163/1688674327163.png\nPageSource: file:///home/runner/.selene/screenshots/1688674327163/1688674327163.html","time":{"start":1688674333208,"stop":1688674344158,"duration":10950}},{"uid":"ea40d1641c1f292f","reportUrl":"https://t-rexamarin.github.io/qaguru/17//#testresult/ea40d1641c1f292f","status":"broken","statusDetails":"TypeError: 'int' object is not callable","time":{"start":1688674207380,"stop":1688674207380,"duration":0}},{"uid":"9e7e58a0d8b0a4e6","reportUrl":"https://t-rexamarin.github.io/qaguru/16//#testresult/9e7e58a0d8b0a4e6","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.header-search-input')).click\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".header-search-input\"}\n  (Session info: headless chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x55f59d1f94e3 <unknown>\n#1 0x55f59cf28c76 <unknown>\n#2 0x55f59cf64c96 <unknown>\n#3 0x55f59cf64dc1 <unknown>\n#4 0x55f59cf9e7f4 <unknown>\n#5 0x55f59cf8403d <unknown>\n#6 0x55f59cf9c30e <unknown>\n#7 0x55f59cf83de3 <unknown>\n#8 0x55f59cf592dd <unknown>\n#9 0x55f59cf5a34e <unknown>\n#10 0x55f59d1b93e4 <unknown>\n#11 0x55f59d1bd3d7 <unknown>\n#12 0x55f59d1c7b20 <unknown>\n#13 0x55f59d1be023 <unknown>\n#14 0x55f59d18c1aa <unknown>\n#15 0x55f59d1e26b8 <unknown>\n#16 0x55f59d1e2847 <unknown>\n#17 0x55f59d1f2243 <unknown>\n#18 0x7ff0af0b6b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1688674071705/1688674071705.png\nPageSource: file:///home/runner/.selene/screenshots/1688674071705/1688674071705.html","time":{"start":1688674078919,"stop":1688674084104,"duration":5185}},{"uid":"4ab0ca7c3441ea78","reportUrl":"https://t-rexamarin.github.io/qaguru/16//#testresult/4ab0ca7c3441ea78","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '.header-search-input')).click\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".header-search-input\"}\n  (Session info: headless chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x56224ae654e3 <unknown>\n#1 0x56224ab94c76 <unknown>\n#2 0x56224abd0c96 <unknown>\n#3 0x56224abd0dc1 <unknown>\n#4 0x56224ac0a7f4 <unknown>\n#5 0x56224abf003d <unknown>\n#6 0x56224ac0830e <unknown>\n#7 0x56224abefde3 <unknown>\n#8 0x56224abc52dd <unknown>\n#9 0x56224abc634e <unknown>\n#10 0x56224ae253e4 <unknown>\n#11 0x56224ae293d7 <unknown>\n#12 0x56224ae33b20 <unknown>\n#13 0x56224ae2a023 <unknown>\n#14 0x56224adf81aa <unknown>\n#15 0x56224ae4e6b8 <unknown>\n#16 0x56224ae4e847 <unknown>\n#17 0x56224ae5e243 <unknown>\n#18 0x7f7ab6819b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1688673972592/1688673972592.png\nPageSource: file:///home/runner/.selene/screenshots/1688673972592/1688673972592.html","time":{"start":1688673979290,"stop":1688673984227,"duration":4937}},{"uid":"6ad33e05852a96d7","reportUrl":"https://t-rexamarin.github.io/qaguru/15//#testresult/6ad33e05852a96d7","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'open'","time":{"start":1688673848059,"stop":1688673848060,"duration":1}},{"uid":"9135d0353a5b156b","reportUrl":"https://t-rexamarin.github.io/qaguru/15//#testresult/9135d0353a5b156b","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'open'","time":{"start":1688673549340,"stop":1688673549340,"duration":0}},{"uid":"eb15f12fcc3f99d7","reportUrl":"https://t-rexamarin.github.io/qaguru/14//#testresult/eb15f12fcc3f99d7","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'open'","time":{"start":1688673184254,"stop":1688673184254,"duration":0}},{"uid":"6d7f471a269b9fd0","reportUrl":"https://t-rexamarin.github.io/qaguru/13//#testresult/6d7f471a269b9fd0","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55c5a0e934e3 <unknown>\n#1 0x55c5a0bc2c76 <unknown>\n#2 0x55c5a0bebd78 <unknown>\n#3 0x55c5a0be8029 <unknown>\n#4 0x55c5a0c26ccc <unknown>\n#5 0x55c5a0c2647f <unknown>\n#6 0x55c5a0c1dde3 <unknown>\n#7 0x55c5a0bf32dd <unknown>\n#8 0x55c5a0bf434e <unknown>\n#9 0x55c5a0e533e4 <unknown>\n#10 0x55c5a0e573d7 <unknown>\n#11 0x55c5a0e61b20 <unknown>\n#12 0x55c5a0e58023 <unknown>\n#13 0x55c5a0e261aa <unknown>\n#14 0x55c5a0e7c6b8 <unknown>\n#15 0x55c5a0e7c847 <unknown>\n#16 0x55c5a0e8c243 <unknown>\n#17 0x7fadd6b11b43 <unknown>","time":{"start":1688672832994,"stop":1688672832994,"duration":0}},{"uid":"4e8a8f7659c6241a","reportUrl":"https://t-rexamarin.github.io/qaguru/11//#testresult/4e8a8f7659c6241a","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x56031d1634e3 <unknown>\n#1 0x56031ce92c76 <unknown>\n#2 0x56031cebbd78 <unknown>\n#3 0x56031ceb8029 <unknown>\n#4 0x56031cef6ccc <unknown>\n#5 0x56031cef647f <unknown>\n#6 0x56031ceedde3 <unknown>\n#7 0x56031cec32dd <unknown>\n#8 0x56031cec434e <unknown>\n#9 0x56031d1233e4 <unknown>\n#10 0x56031d1273d7 <unknown>\n#11 0x56031d131b20 <unknown>\n#12 0x56031d128023 <unknown>\n#13 0x56031d0f61aa <unknown>\n#14 0x56031d14c6b8 <unknown>\n#15 0x56031d14c847 <unknown>\n#16 0x56031d15c243 <unknown>\n#17 0x7f5034b9ab43 <unknown>","time":{"start":1688672438677,"stop":1688672438677,"duration":0}},{"uid":"8fe0a835504ffa2b","reportUrl":"https://t-rexamarin.github.io/qaguru/10//#testresult/8fe0a835504ffa2b","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55ab4715b4e3 <unknown>\n#1 0x55ab46e8ac76 <unknown>\n#2 0x55ab46eb3d78 <unknown>\n#3 0x55ab46eb0029 <unknown>\n#4 0x55ab46eeeccc <unknown>\n#5 0x55ab46eee47f <unknown>\n#6 0x55ab46ee5de3 <unknown>\n#7 0x55ab46ebb2dd <unknown>\n#8 0x55ab46ebc34e <unknown>\n#9 0x55ab4711b3e4 <unknown>\n#10 0x55ab4711f3d7 <unknown>\n#11 0x55ab47129b20 <unknown>\n#12 0x55ab47120023 <unknown>\n#13 0x55ab470ee1aa <unknown>\n#14 0x55ab471446b8 <unknown>\n#15 0x55ab47144847 <unknown>\n#16 0x55ab47154243 <unknown>\n#17 0x7ff214097b43 <unknown>","time":{"start":1688672164185,"stop":1688672164185,"duration":0}},{"uid":"23b1d28c373f8357","reportUrl":"https://t-rexamarin.github.io/qaguru/9//#testresult/23b1d28c373f8357","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'open'","time":{"start":1688671590150,"stop":1688671590150,"duration":0}},{"uid":"937a15f07ab7d2a","reportUrl":"https://t-rexamarin.github.io/qaguru/8//#testresult/937a15f07ab7d2a","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'open'","time":{"start":1688670597726,"stop":1688670597727,"duration":1}},{"uid":"8ca5a919e06d13f5","reportUrl":"https://t-rexamarin.github.io/qaguru/7//#testresult/8ca5a919e06d13f5","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x561998c904e3 <unknown>\n#1 0x5619989bfc76 <unknown>\n#2 0x5619989e8d78 <unknown>\n#3 0x5619989e5029 <unknown>\n#4 0x561998a23ccc <unknown>\n#5 0x561998a2347f <unknown>\n#6 0x561998a1ade3 <unknown>\n#7 0x5619989f02dd <unknown>\n#8 0x5619989f134e <unknown>\n#9 0x561998c503e4 <unknown>\n#10 0x561998c543d7 <unknown>\n#11 0x561998c5eb20 <unknown>\n#12 0x561998c55023 <unknown>\n#13 0x561998c231aa <unknown>\n#14 0x561998c796b8 <unknown>\n#15 0x561998c79847 <unknown>\n#16 0x561998c89243 <unknown>\n#17 0x7efdeb586b43 <unknown>","time":{"start":1688669610081,"stop":1688669610081,"duration":0}},{"uid":"269ab77589ed1ada","reportUrl":"https://t-rexamarin.github.io/qaguru/6//#testresult/269ab77589ed1ada","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x560c090e24e3 <unknown>\n#1 0x560c08e11c76 <unknown>\n#2 0x560c08e3ad78 <unknown>\n#3 0x560c08e37029 <unknown>\n#4 0x560c08e75ccc <unknown>\n#5 0x560c08e7547f <unknown>\n#6 0x560c08e6cde3 <unknown>\n#7 0x560c08e422dd <unknown>\n#8 0x560c08e4334e <unknown>\n#9 0x560c090a23e4 <unknown>\n#10 0x560c090a63d7 <unknown>\n#11 0x560c090b0b20 <unknown>\n#12 0x560c090a7023 <unknown>\n#13 0x560c090751aa <unknown>\n#14 0x560c090cb6b8 <unknown>\n#15 0x560c090cb847 <unknown>\n#16 0x560c090db243 <unknown>\n#17 0x7fdcd5cf0b43 <unknown>","time":{"start":1688668475780,"stop":1688668475780,"duration":0}},{"uid":"8570faaf539135a5","reportUrl":"https://t-rexamarin.github.io/qaguru/4//#testresult/8570faaf539135a5","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5580d512b4e3 <unknown>\n#1 0x5580d4e5ac76 <unknown>\n#2 0x5580d4e83d78 <unknown>\n#3 0x5580d4e80029 <unknown>\n#4 0x5580d4ebeccc <unknown>\n#5 0x5580d4ebe47f <unknown>\n#6 0x5580d4eb5de3 <unknown>\n#7 0x5580d4e8b2dd <unknown>\n#8 0x5580d4e8c34e <unknown>\n#9 0x5580d50eb3e4 <unknown>\n#10 0x5580d50ef3d7 <unknown>\n#11 0x5580d50f9b20 <unknown>\n#12 0x5580d50f0023 <unknown>\n#13 0x5580d50be1aa <unknown>\n#14 0x5580d51146b8 <unknown>\n#15 0x5580d5114847 <unknown>\n#16 0x5580d5124243 <unknown>\n#17 0x7f089eba7b43 <unknown>","time":{"start":1688667982026,"stop":1688667982026,"duration":0}},{"uid":"4fcf4dea3c3e5172","reportUrl":"https://t-rexamarin.github.io/qaguru/3//#testresult/4fcf4dea3c3e5172","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5601c9bff4e3 <unknown>\n#1 0x5601c992ec76 <unknown>\n#2 0x5601c9957d78 <unknown>\n#3 0x5601c9954029 <unknown>\n#4 0x5601c9992ccc <unknown>\n#5 0x5601c999247f <unknown>\n#6 0x5601c9989de3 <unknown>\n#7 0x5601c995f2dd <unknown>\n#8 0x5601c996034e <unknown>\n#9 0x5601c9bbf3e4 <unknown>\n#10 0x5601c9bc33d7 <unknown>\n#11 0x5601c9bcdb20 <unknown>\n#12 0x5601c9bc4023 <unknown>\n#13 0x5601c9b921aa <unknown>\n#14 0x5601c9be86b8 <unknown>\n#15 0x5601c9be8847 <unknown>\n#16 0x5601c9bf8243 <unknown>\n#17 0x7fa75b16db43 <unknown>","time":{"start":1688662443481,"stop":1688662443481,"duration":0}}]},"tags":["web"]},"source":"7c4a9481a648b78f.json","parameterValues":[]}